"""Pure checks for LAN service composition; no service or network mutation."""
from __future__ import annotations

import importlib.util
import tempfile
import unittest
from pathlib import Path


ROOT=Path(__file__).resolve().parents[1]
SPEC=importlib.util.spec_from_file_location('monik_enable_lan',ROOT/'scripts/enable-lan.py')
LAN=importlib.util.module_from_spec(SPEC);SPEC.loader.exec_module(LAN)


class LanSetup(unittest.TestCase):
    def test_unprivileged_port_uses_owner_user_service(self):
        unit=LAN.service_unit('jericho',Path('/home/jericho'),ROOT,
                              Path('/home/jericho/.config/monik/config.json'),
                              Path('/home/jericho/.local/share/monik'),8443,user_service=True)
        self.assertIn('# Generated by monik installer',unit)
        self.assertIn('# HTTPS LAN mode',unit)
        self.assertNotIn('User=jericho',unit)
        self.assertNotIn('CAP_NET_BIND_SERVICE',unit)
        self.assertNotIn('CapabilityBoundingSet',unit)
        self.assertIn('WantedBy=default.target',unit)

    def test_low_port_system_service_has_only_scoped_bind_capability(self):
        unit=LAN.service_unit('jericho',Path('/home/jericho'),ROOT,
                              Path('/home/jericho/.config/monik/config.json'),
                              Path('/home/jericho/.local/share/monik'),666,user_service=False)
        self.assertIn('User=jericho',unit)
        self.assertIn('AmbientCapabilities=CAP_NET_BIND_SERVICE',unit)
        self.assertIn('CapabilityBoundingSet=CAP_NET_BIND_SERVICE',unit)
        self.assertNotIn('setcap',unit)
        self.assertIn('WantedBy=multi-user.target',unit)

    def test_installer_preserves_high_port_lan_configuration(self):
        source=(ROOT/'scripts/install.sh').read_text()
        self.assertNotIn('User-служба предназначена для loopback',source)
        self.assertIn('tls_ca',source)

    def test_user_unit_atomic_write_accepts_standard_non_writable_0755_directory(self):
        with tempfile.TemporaryDirectory() as folder:
            directory=Path(folder)/'systemd/user';directory.mkdir(parents=True);directory.chmod(0o755)
            path=directory/'monik.service';first=b'# Generated by monik installer\nfirst\n'
            second=b'# Generated by monik installer\nsecond\n'
            LAN.write_user_unit(path,first);self.assertEqual(path.read_bytes(),first)
            self.assertEqual(path.stat().st_mode & 0o777,0o600)
            LAN.write_user_unit(path,second);self.assertEqual(path.read_bytes(),second)
            directory.chmod(0o777)
            with self.assertRaises(ValueError):LAN.write_user_unit(path,first)
            directory.chmod(0o755)


if __name__=='__main__':unittest.main(verbosity=2)
