#!/usr/bin/env python3
"""Explicit owner-only LAN setup. Never changes IP addresses, routing or firewall.

Creates a local CA/leaf certificate and an unprivileged system service. The only
optional service capability is CAP_NET_BIND_SERVICE for a requested port < 1024.
Does not set capabilities on Python and does not change global sysctl settings.
"""
from __future__ import annotations
import argparse,getpass,ipaddress,json,os,shutil,subprocess,sys,tempfile
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];sys.path.insert(0,str(ROOT))
from monik.config import load
from monik.cli import write_config


def run(*args):subprocess.run(args,check=True)
def main():
    ap=argparse.ArgumentParser(description='Явное включение HTTPS в LAN');ap.add_argument('ip');ap.add_argument('port',type=int,nargs='?',default=8443);args=ap.parse_args()
    if os.geteuid()==0:raise ValueError('Run as the ordinary owner; only unit installation requests sudo')
    os.umask(0o077);address=ipaddress.ip_address(args.ip)
    if address.version!=4 or not address.is_private or address.is_loopback or address.is_unspecified or address.is_multicast:raise ValueError('Expected one explicit private LAN IPv4 address')
    if not 1<=args.port<=65535:raise ValueError('Port must be 1..65535')
    for cmd in ('ip','openssl','sudo','systemctl','ss'):
        if not shutil.which(cmd):raise ValueError('Required local tool is missing: '+cmd)
    info=json.loads(subprocess.check_output(['ip','-j','address','show'],text=True))
    assigned={a.get('local') for i in info for a in i.get('addr_info',[])}
    if str(address) not in assigned:raise ValueError('This IP is not assigned to this machine. No address, route or firewall was changed.')
    home=Path.home();config_path=home/'.config/monik/config.json';config=load(config_path);user=getpass.getuser()
    for value in (str(home),str(ROOT),config['data_dir'],user):
        if any(c.isspace() for c in value) or '%' in value or '"' in value or "'" in value:raise ValueError('Use paths and user names without whitespace, quotes or %')
    if not (ROOT/'.venv/bin/python').exists():raise ValueError('Run scripts/install.sh first')
    from monik.sandbox import abi
    if abi()<3:raise ValueError('Landlock ABI >= 3 is required')
    sockets=subprocess.check_output(['ss','-H','-ltn'],text=True)
    if any(line.split()[3].rsplit(':',1)[-1]==str(args.port) for line in sockets.splitlines() if len(line.split())>=4):raise ValueError('Requested TCP port is already in use; choose a free port')
    destination=Path('/etc/systemd/system/monik.service')
    if destination.exists() and '# Generated by monik LAN setup' not in destination.read_text():raise ValueError('Refusing to replace an unrelated system unit')
    tls=config_path.parent/'tls';tls.mkdir(mode=0o700,exist_ok=True);ca=tls/'monik-ca.crt';ca_key=tls/'monik-ca.key';key=tls/'server.key';cert=tls/'server.crt'
    if ca.exists()!=ca_key.exists():raise ValueError('Incomplete existing CA; inspect the private TLS directory')
    if not ca.exists():
        run('openssl','req','-x509','-newkey','rsa:3072','-sha256','-days','3650','-nodes','-keyout',str(ca_key),'-out',str(ca),'-subj','/CN=monik Local CA','-addext','basicConstraints=critical,CA:TRUE','-addext','keyUsage=critical,keyCertSign,cRLSign')
    with tempfile.TemporaryDirectory(dir=tls) as temp:
        t=Path(temp);csr=t/'server.csr';leaf_key=t/'server.key';leaf=t/'server.crt';extensions=t/'extensions.cnf'
        extensions.write_text(f'basicConstraints=critical,CA:FALSE\nkeyUsage=critical,digitalSignature,keyEncipherment\nextendedKeyUsage=serverAuth\nsubjectAltName=IP:{address}\n')
        run('openssl','req','-new','-newkey','rsa:2048','-nodes','-keyout',str(leaf_key),'-out',str(csr),'-subj','/CN=monik')
        run('openssl','x509','-req','-in',str(csr),'-CA',str(ca),'-CAkey',str(ca_key),'-CAcreateserial','-out',str(leaf),'-days','365','-sha256','-extfile',str(extensions))
        run('openssl','verify','-CAfile',str(ca),str(leaf));os.replace(leaf_key,key);os.replace(leaf,cert)
    key.chmod(0o600);ca_key.chmod(0o600);ca.chmod(0o644);cert.chmod(0o644)
    backup=config_path.parent/'config.before-lan.json'
    if not backup.exists():shutil.copy2(config_path,backup);backup.chmod(0o600)
    config.pop('_path',None);config.update(bind=str(address),port=args.port,tls_cert=str(cert),tls_key=str(key));write_config(config_path,config)
    data=Path(config['data_dir']);data.mkdir(mode=0o700,parents=True,exist_ok=True)
    capabilities='AmbientCapabilities=CAP_NET_BIND_SERVICE\nCapabilityBoundingSet=CAP_NET_BIND_SERVICE' if args.port<1024 else 'CapabilityBoundingSet='
    unit=f'''# Generated by monik LAN setup
[Unit]
Description=monik read-only Codex Observatory (HTTPS LAN)
After=network-online.target
Wants=network-online.target
[Service]
Type=simple
User={user}
WorkingDirectory={ROOT}
Environment=PYTHONPATH={ROOT}
Environment=PYTHONDONTWRITEBYTECODE=1
ExecStart={ROOT}/.venv/bin/python -m monik serve --config {config_path}
Restart=on-failure
RestartSec=5
TimeoutStopSec=20
UMask=0077
Nice=10
NoNewPrivileges=true
ProtectSystem=strict
ProtectHome=read-only
ReadWritePaths={data}
PrivateTmp=true
{capabilities}
[Install]
WantedBy=multi-user.target
'''
    unit_file=config_path.parent/'monik-lan.service';unit_file.write_text(unit)
    print(unit);print('Будет установлен только этот systemd unit. IP, маршрутизация и firewall не изменяются.',flush=True)
    subprocess.run(['systemctl','--user','disable','--now','monik.service'],check=False)
    run('sudo','install','-o','root','-g','root','-m','644',str(unit_file),str(destination));run('sudo','systemctl','daemon-reload');run('sudo','systemctl','enable','--now','monik.service')
    print(f'HTTPS: https://{address}:{args.port}\nПубличный сертификат CA для устройства: {ca}\nТокен: ~/.local/bin/monik token\nFirewall не открывался. Разреши TCP только нужному LAN-клиенту.\nНикогда не передавай файлы .key.')

if __name__=='__main__':
    try:main()
    except (OSError,ValueError,subprocess.CalledProcessError) as exc:raise SystemExit('monik LAN: '+str(exc))
