#!/usr/bin/env python3
"""Enable authenticated HTTPS on one explicitly assigned private LAN address.

Ports >= 1024 stay in the existing owner user service and need no sudo. A low
port uses the system unit only to grant CAP_NET_BIND_SERVICE to this service;
the application still runs as the ordinary owner.
"""
from __future__ import annotations

import argparse
import getpass
import ipaddress
import json
import os
import shutil
import ssl
import stat
import subprocess
import sys
import tempfile
import time
from pathlib import Path
from urllib.request import HTTPSHandler,ProxyHandler,build_opener

ROOT=Path(__file__).resolve().parents[1]
sys.path.insert(0,str(ROOT))
from monik.cli import write_config
from monik.config import atomic_private_write,load,private_directory


def run(*args):
    subprocess.run(args,check=True)


def service_unit(user: str,home: Path,root: Path,config_path: Path,data: Path,
                 port: int,*,user_service: bool) -> str:
    marker='# Generated by monik installer\n# HTTPS LAN mode' if user_service else '# Generated by monik LAN setup'
    identity='' if user_service else f'User={user}\n'
    capabilities=('AmbientCapabilities=CAP_NET_BIND_SERVICE\nCapabilityBoundingSet=CAP_NET_BIND_SERVICE'
                  if not user_service and port<1024 else '')
    target='default.target' if user_service else 'multi-user.target'
    return f'''{marker}
[Unit]
Description=monik read-only Codex Observatory (HTTPS LAN)
After=network-online.target
Wants=network-online.target
[Service]
Type=simple
{identity}WorkingDirectory={home}
Environment=PYTHONDONTWRITEBYTECODE=1
ExecStart={root}/.venv/bin/python -I -B -m monik serve --config {config_path}
Restart=on-failure
RestartSec=5
TimeoutStopSec=20
UMask=0077
Nice=10
NoNewPrivileges=true
ProtectSystem=strict
ProtectHome=read-only
ReadWritePaths={data}
PrivateTmp=true
{capabilities}
[Install]
WantedBy={target}
'''


def generated_user_unit(path: Path) -> bytes | None:
    if not os.path.lexists(path): return None
    info=path.lstat()
    if (not stat.S_ISREG(info.st_mode) or info.st_nlink!=1 or
            info.st_uid!=os.geteuid() or info.st_mode & 0o077):
        raise ValueError('Refusing to replace an unsafe user unit')
    content=path.read_bytes()
    if b'# Generated by monik installer' not in content:
        raise ValueError('Refusing to replace an unrelated user unit')
    return content


def write_user_unit(path: Path,content: bytes) -> None:
    """Atomically replace our 0600 unit in a conventional owner-controlled 0755 dir."""
    parent=path.parent;directory=parent.lstat()
    if (not stat.S_ISDIR(directory.st_mode) or directory.st_uid!=os.geteuid()
            or directory.st_mode & 0o022 or parent.is_symlink()):
        raise ValueError('User unit directory must be owner-controlled and not writable by others')
    old=path.lstat() if os.path.lexists(path) else None
    if old is not None:generated_user_unit(path)
    fd,name=tempfile.mkstemp(prefix='.monik.service.',dir=parent);temporary=Path(name)
    try:
        os.fchmod(fd,0o600)
        with os.fdopen(fd,'wb') as stream:
            stream.write(content);stream.flush();os.fsync(stream.fileno())
        if old is None:
            os.link(temporary,path,follow_symlinks=False);temporary.unlink()
        else:
            current=path.lstat();generated_user_unit(path)
            if (current.st_dev,current.st_ino)!=(old.st_dev,old.st_ino):
                raise ValueError('User unit changed during update')
            os.replace(temporary,path)
        handle=os.open(parent,os.O_RDONLY|os.O_DIRECTORY|os.O_CLOEXEC)
        try:os.fsync(handle)
        finally:os.close(handle)
    except BaseException:
        try:os.close(fd)
        except OSError:pass
        try:temporary.unlink()
        except FileNotFoundError:pass
        raise


def https_ready(address,port,ca):
    context=ssl.create_default_context(cafile=str(ca))
    opener=build_opener(ProxyHandler({}),HTTPSHandler(context=context))
    deadline=time.monotonic()+12;last=None
    while time.monotonic()<deadline:
        try:
            with opener.open(f'https://{address}:{port}/',timeout=1) as response:
                if response.status==200:return
                last=ValueError('unexpected HTTPS status')
        except OSError as exc:
            last=exc
        time.sleep(.1)
    raise ValueError('HTTPS service did not become ready') from last


def restore_leaf(snapshot):
    for path,content,mode in snapshot:
        if content is None:
            try:path.unlink()
            except FileNotFoundError:pass
        else:
            atomic_private_write(path,content);path.chmod(mode)


def main():
    ap=argparse.ArgumentParser(description='Включить HTTPS на явном LAN-адресе')
    ap.add_argument('ip');ap.add_argument('port',type=int,nargs='?',default=8443)
    args=ap.parse_args()
    if os.geteuid()==0:raise ValueError('Run as the ordinary owner')
    os.umask(0o077);address=ipaddress.ip_address(args.ip);user_service=args.port>=1024
    if (address.version!=4 or not address.is_private or address.is_loopback or
            address.is_unspecified or address.is_multicast):
        raise ValueError('Expected one explicit private LAN IPv4 address')
    if not 1<=args.port<=65535:raise ValueError('Port must be 1..65535')
    required=['ip','openssl','systemctl','ss']+([] if user_service else ['sudo'])
    for cmd in required:
        if not shutil.which(cmd):raise ValueError('Required local tool is missing: '+cmd)
    assigned={a.get('local') for i in json.loads(subprocess.check_output(
        ['ip','-j','address','show'],text=True)) for a in i.get('addr_info',[])}
    if str(address) not in assigned:
        raise ValueError('This IP is not assigned to this machine; network settings were not changed')
    home=Path.home();config_path=home/'.config/monik/config.json';config=load(config_path);user=getpass.getuser()
    for value in (str(home),str(ROOT),config['data_dir'],user):
        if any(c.isspace() for c in value) or '%' in value or '"' in value or "'" in value:
            raise ValueError('Use paths and user names without whitespace, quotes or %')
    if not (ROOT/'.venv/bin/python').exists():raise ValueError('Run scripts/install.sh first')
    from monik.sandbox import abi
    if abi()<3:raise ValueError('Landlock ABI >= 3 is required')
    sockets=subprocess.check_output(['ss','-H','-ltn'],text=True)
    if any(line.split()[3].rsplit(':',1)[-1]==str(args.port)
           for line in sockets.splitlines() if len(line.split())>=4):
        raise ValueError('Requested TCP port is already in use')

    user_unit=home/'.config/systemd/user/monik.service';old_user=generated_user_unit(user_unit)
    user_active=subprocess.run(['systemctl','--user','is-active','--quiet','monik.service'],
        stdout=subprocess.DEVNULL,stderr=subprocess.DEVNULL).returncode==0
    user_enabled=subprocess.run(['systemctl','--user','is-enabled','--quiet','monik.service'],
        stdout=subprocess.DEVNULL,stderr=subprocess.DEVNULL).returncode==0
    system_active=subprocess.run(['systemctl','is-active','--quiet','monik.service'],
        stdout=subprocess.DEVNULL,stderr=subprocess.DEVNULL).returncode==0
    system_enabled=subprocess.run(['systemctl','is-enabled','--quiet','monik.service'],
        stdout=subprocess.DEVNULL,stderr=subprocess.DEVNULL).returncode==0
    destination=Path('/etc/systemd/system/monik.service');old_system=None
    system_load=subprocess.check_output(['systemctl','show','monik.service','-p','LoadState','--value'],text=True).strip()
    system_fragment=subprocess.check_output(['systemctl','show','monik.service','-p','FragmentPath','--value'],text=True).strip()
    if user_service and (system_active or system_enabled or system_load not in ('','not-found')):
        raise ValueError('A system monik service exists; refusing to create a second service')
    if not user_service:
        if system_load not in ('','not-found') and (not system_fragment or Path(system_fragment)!=destination):
            raise ValueError('Refusing to shadow a system monik service from another location')
        if os.path.lexists(destination):
            info=destination.lstat()
            if (not stat.S_ISREG(info.st_mode) or info.st_nlink!=1 or info.st_uid!=0 or
                    '# Generated by monik LAN setup' not in destination.read_text()):
                raise ValueError('Refusing to replace an unrelated system unit')
            old_system=destination.read_bytes()

    tls=private_directory(config_path.parent/'tls',create=True)
    ca=tls/'monik-ca.crt';ca_key=tls/'monik-ca.key';key=tls/'server.key';cert=tls/'server.crt';serial=tls/'monik-ca.srl'
    for path in (ca,ca_key,key,cert,serial):
        if os.path.lexists(path):
            info=path.lstat()
            if not stat.S_ISREG(info.st_mode) or info.st_nlink!=1 or info.st_uid!=os.geteuid():
                raise ValueError('TLS files must be ordinary single-link files owned by this user')
    if ca.exists()!=ca_key.exists():raise ValueError('Incomplete existing CA')
    leaf_before=[(path,path.read_bytes() if path.exists() else None,mode)
                 for path,mode in ((key,0o600),(cert,0o644))]
    if not ca.exists():
        run('openssl','req','-x509','-newkey','rsa:3072','-sha256','-days','3650','-nodes',
            '-keyout',str(ca_key),'-out',str(ca),'-subj','/CN=monik Local CA',
            '-addext','basicConstraints=critical,CA:TRUE','-addext','keyUsage=critical,keyCertSign,cRLSign')
    with tempfile.TemporaryDirectory(dir=tls) as temp:
        t=Path(temp);csr=t/'server.csr';leaf_key=t/'server.key';leaf=t/'server.crt';extensions=t/'extensions.cnf'
        extensions.write_text(f'basicConstraints=critical,CA:FALSE\nkeyUsage=critical,digitalSignature,keyEncipherment\nextendedKeyUsage=serverAuth\nsubjectAltName=IP:{address}\n')
        run('openssl','req','-new','-newkey','rsa:2048','-nodes','-keyout',str(leaf_key),'-out',str(csr),'-subj','/CN=monik')
        run('openssl','x509','-req','-in',str(csr),'-CA',str(ca),'-CAkey',str(ca_key),
            '-CAcreateserial','-out',str(leaf),'-days','365','-sha256','-extfile',str(extensions))
        run('openssl','verify','-CAfile',str(ca),str(leaf))
        try:os.replace(leaf_key,key);os.replace(leaf,cert)
        except OSError:
            restore_leaf(leaf_before);raise
    key.chmod(0o600);ca_key.chmod(0o600);serial.chmod(0o600);ca.chmod(0o644);cert.chmod(0o644)

    config.pop('_path',None);original=dict(config)
    backup=config_path.parent/'config.before-lan.json'
    if os.path.lexists(backup):load(backup)
    else:write_config(backup,original)
    config.update(bind=str(address),port=args.port,tls_cert=str(cert),tls_key=str(key),tls_ca=str(ca))
    data=private_directory(config['data_dir'],create=True)
    unit=service_unit(user,home,ROOT,config_path,data,args.port,user_service=user_service)
    staged=config_path.parent/'monik-lan.service';atomic_private_write(staged,unit.encode())
    changed=False;installed=False
    try:
        write_config(config_path,config);changed=True
        if user_service:
            if user_active:run('systemctl','--user','stop','monik.service')
            write_user_unit(user_unit,unit.encode());installed=True
            run('systemctl','--user','daemon-reload');run('systemctl','--user','enable','--now','monik.service')
        else:
            if user_active or user_enabled:run('systemctl','--user','disable','--now','monik.service')
            if system_active:run('sudo','systemctl','stop','monik.service')
            run('sudo','install','-o','root','-g','root','-m','644',str(staged),str(destination));installed=True
            run('sudo','systemctl','daemon-reload');run('sudo','systemctl','enable','--now','monik.service')
        https_ready(address,args.port,ca)
        from monik.client import Client
        Client(load(config_path)).get('overview')
    except (OSError,ValueError,subprocess.CalledProcessError):
        if changed:write_config(config_path,original)
        restore_leaf(leaf_before)
        if user_service:
            subprocess.run(['systemctl','--user','disable','--now','monik.service'],check=False)
            if installed:
                if old_user is None:
                    try:user_unit.unlink()
                    except FileNotFoundError:pass
                else:write_user_unit(user_unit,old_user)
            subprocess.run(['systemctl','--user','daemon-reload'],check=False)
            if user_enabled:subprocess.run(['systemctl','--user','enable','monik.service'],check=False)
            if user_active:subprocess.run(['systemctl','--user','start','monik.service'],check=False)
        else:
            if installed:
                subprocess.run(['sudo','systemctl','disable','--now','monik.service'],check=False)
                if old_system is not None:
                    previous=config_path.parent/'monik-lan.previous.service';atomic_private_write(previous,old_system)
                    subprocess.run(['sudo','install','-o','root','-g','root','-m','644',str(previous),str(destination)],check=False)
                else:
                    subprocess.run(['sudo','rm','-f','--',str(destination)],check=False)
                subprocess.run(['sudo','systemctl','daemon-reload'],check=False)
            if system_enabled:subprocess.run(['sudo','systemctl','enable','monik.service'],check=False)
            if system_active:subprocess.run(['sudo','systemctl','start','monik.service'],check=False)
            if user_enabled:subprocess.run(['systemctl','--user','enable','monik.service'],check=False)
            if user_active:subprocess.run(['systemctl','--user','start','monik.service'],check=False)
        raise
    mode='user-служба без sudo' if user_service else 'system-служба с capability только на bind порта'
    print(f'HTTPS: https://{address}:{args.port}\nРежим: {mode}\nПубличный CA: {ca}\n'
          'Токен: ~/.local/bin/monik token\nFirewall не изменялся; передавай устройству только .crt, никогда .key.')


if __name__=='__main__':
    try:main()
    except (OSError,ValueError,subprocess.CalledProcessError) as exc:
        raise SystemExit('monik LAN: '+str(exc))
