#!/usr/bin/env bash
set -euo pipefail
umask 077
if (( EUID == 0 )); then echo 'Запусти установщик обычным пользователем, не через sudo.' >&2; exit 1; fi
START=1
if [[ ${1:-} == --no-start ]]; then START=0; elif [[ $# != 0 ]]; then echo 'Использование: bash scripts/install.sh [--no-start]' >&2; exit 2; fi
ROOT=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)
case "$ROOT$HOME" in *[[:space:]%]* ) echo 'Для этой версии выбери каталог без пробелов и %.' >&2; exit 1;; esac
command -v python3 >/dev/null || { echo 'Нужен Python 3.11+.' >&2; exit 1; }
python3 -c 'import sys,sqlite3; assert sys.version_info >= (3,11), "Python 3.11+ required"; c=sqlite3.connect(":memory:"); c.execute("CREATE VIRTUAL TABLE t USING fts5(x)")'
python3 -m venv "$ROOT/.venv"
"$ROOT/.venv/bin/python" -m pip install --disable-pip-version-check --only-binary=:all: -r "$ROOT/requirements.lock"
mkdir -p "$HOME/.local/bin" "$HOME/.config/systemd/user"
printf '#!/usr/bin/env bash\nset -euo pipefail\nexport PYTHONPATH=%q\nexport PYTHONDONTWRITEBYTECODE=1\nexec %q -m monik "$@"\n' "$ROOT" "$ROOT/.venv/bin/python" > "$HOME/.local/bin/monik"
chmod 700 "$HOME/.local/bin/monik"
"$HOME/.local/bin/monik" init
"$HOME/.local/bin/monik" doctor
UNIT="$HOME/.config/systemd/user/monik.service"
if [[ -e "$UNIT" ]] && ! grep -q '^# Generated by monik installer' "$UNIT"; then
  echo "Не заменяю чужой unit: $UNIT" >&2; exit 1
fi
cat > "$UNIT" <<UNIT
# Generated by monik installer
[Unit]
Description=monik read-only Codex Observatory
After=network.target
[Service]
Type=simple
WorkingDirectory=$ROOT
Environment=PYTHONPATH=$ROOT
Environment=PYTHONDONTWRITEBYTECODE=1
ExecStart=$ROOT/.venv/bin/python -m monik serve --config $HOME/.config/monik/config.json
Restart=on-failure
RestartSec=5
TimeoutStopSec=20
UMask=0077
NoNewPrivileges=true
Nice=10
[Install]
WantedBy=default.target
UNIT
chmod 600 "$UNIT"
if (( START )); then
  PYTHONPATH="$ROOT" "$ROOT/.venv/bin/python" -c "from monik.sandbox import abi;assert abi()>=3,'Landlock ABI >= 3 required; no unsafe fallback. Inspect monik doctor.'"
  systemctl --user daemon-reload
  systemctl --user enable --now monik.service
  sleep 1
  systemctl --user is-active --quiet monik.service || { journalctl --user -u monik.service -n 25 --no-pager; exit 1; }
fi
printf '\nУстановка завершена. По умолчанию: http://127.0.0.1:8666\nТокен: %s/.local/bin/monik token\n' "$HOME"
printf 'Журнал: journalctl --user -u monik.service -f\nИсходники Codex и его процессы не изменялись установщиком.\n'
