#!/usr/bin/env bash
set -euo pipefail
umask 077

if (( EUID == 0 )); then echo 'Запусти установщик обычным пользователем, не через sudo.' >&2; exit 1; fi
START=1
if [[ ${1:-} == --no-start ]]; then START=0; elif [[ $# != 0 ]]; then echo 'Использование: bash scripts/install.sh [--no-start]' >&2; exit 2; fi

ROOT=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd -P)
CONFIG=$HOME/.config/monik/config.json
LAUNCHER=$HOME/.local/bin/monik
UNIT=$HOME/.config/systemd/user/monik.service
STAMP=$(date -u +%Y%m%dT%H%M%SZ)-$$
STATE=$HOME/.local/share/monik
ROLLBACK=$STATE/rollback/$STAMP
STAGE=$ROOT/.venv.install.$STAMP
PACKAGE=$STATE/.package.$STAMP
OLD_VENV=
WAS_ACTIVE=0
WAS_ENABLED=0
MUTATED=0
NEW_VENV=0

case "$ROOT$HOME" in *[[:space:]%\"\']* ) echo 'Для этой версии выбери пути без пробелов, кавычек и %.' >&2; exit 1;; esac
command -v python3 >/dev/null || { echo 'Нужен Python 3.11+.' >&2; exit 1; }
command -v systemctl >/dev/null || { echo 'Нужен пользовательский systemd.' >&2; exit 1; }
python3 -c 'import sys,sqlite3; assert sys.version_info >= (3,11), "Python 3.11+ required"; c=sqlite3.connect(":memory:"); c.execute("CREATE VIRTUAL TABLE t USING fts5(x)")'

for directory in "$HOME/.local" "$HOME/.local/bin" "$HOME/.config" "$HOME/.config/systemd" "$HOME/.config/systemd/user" "$STATE" "$STATE/rollback"; do
  [[ ! -L $directory ]] || { echo "Не использую символическую ссылку для собственного каталога: $directory" >&2; exit 1; }
done
mkdir -p "$HOME/.local/bin" "$HOME/.config/systemd/user" "$STATE/rollback"
chmod 700 "$STATE" "$STATE/rollback"

safe_owned_file() {
  local path=$1
  [[ ! -L $path && -f $path ]] || { echo "Небезопасный файл: $path" >&2; return 1; }
  [[ $(stat -c %u -- "$path") == "$EUID" && $(stat -c %h -- "$path") == 1 ]] || { echo "Чужой или многоссылочный файл: $path" >&2; return 1; }
}

if [[ -e $UNIT || -L $UNIT ]]; then
  safe_owned_file "$UNIT"
  grep -q '^# Generated by monik installer' "$UNIT" || { echo "Не заменяю чужой unit: $UNIT" >&2; exit 1; }
fi
if [[ -e $LAUNCHER || -L $LAUNCHER ]]; then
  safe_owned_file "$LAUNCHER"
  grep -Eq '^# Generated by monik installer|exec .+ -m monik ' "$LAUNCHER" || { echo "Не заменяю чужой launcher: $LAUNCHER" >&2; exit 1; }
fi

SYSTEM_LOAD=$(systemctl show monik.service -p LoadState --value 2>/dev/null || true)
USER_LOAD=$(systemctl --user show monik.service -p LoadState --value 2>/dev/null || true)
USER_FRAGMENT=$(systemctl --user show monik.service -p FragmentPath --value 2>/dev/null || true)
SYSTEM_ACTIVE=0; USER_ACTIVE=0; USER_ENABLED=0
systemctl is-active --quiet monik.service 2>/dev/null && SYSTEM_ACTIVE=1 || true
systemctl --user is-active --quiet monik.service 2>/dev/null && USER_ACTIVE=1 || true
systemctl --user is-enabled --quiet monik.service 2>/dev/null && USER_ENABLED=1 || true
if (( SYSTEM_ACTIVE && USER_ACTIVE )); then echo 'Одновременно активны user и system службы monik; останови одну перед обновлением.' >&2; exit 1; fi
if (( SYSTEM_ACTIVE )) || [[ $SYSTEM_LOAD != not-found && -n $SYSTEM_LOAD ]]; then
  echo 'Обнаружена system-служба monik. User-установщик не создаёт вторую; используй один выбранный вариант.' >&2; exit 1
fi
if [[ $USER_LOAD != not-found && -n $USER_LOAD ]] && [[ -z $USER_FRAGMENT || $USER_FRAGMENT != "$UNIT" ]]; then
  echo 'Обнаружена user-служба monik из другого расположения; установка остановлена.' >&2; exit 1
fi
if (( USER_ACTIVE || USER_ENABLED )) && [[ ! -f $UNIT ]]; then echo 'Активна или включена неизвестная user-служба monik; установка остановлена.' >&2; exit 1; fi
WAS_ACTIVE=$USER_ACTIVE
WAS_ENABLED=$USER_ENABLED

[[ ! -e $STAGE && ! -L $STAGE ]] || { echo "Временный каталог уже существует: $STAGE" >&2; exit 1; }
[[ ! -e $PACKAGE && ! -L $PACKAGE ]] || { echo "Временный каталог уже существует: $PACKAGE" >&2; exit 1; }
cleanup_preflight() { rm -rf -- "$STAGE" "$PACKAGE"; }
trap cleanup_preflight EXIT INT TERM
python3 -m venv "$STAGE"
"$STAGE/bin/python" -m pip install --disable-pip-version-check --only-binary=:all: -r "$ROOT/requirements.lock"
"$STAGE/bin/python" -m pip install --disable-pip-version-check --only-binary=:all: 'setuptools==78.1.1'
mkdir "$PACKAGE";chmod 700 "$PACKAGE"
cp -- "$ROOT/pyproject.toml" "$PACKAGE/pyproject.toml"
"$STAGE/bin/python" - "$ROOT/monik" "$PACKAGE/monik" <<'PY'
import shutil,sys
shutil.copytree(sys.argv[1],sys.argv[2],ignore=shutil.ignore_patterns('__pycache__','*.pyc','*.pyo'))
PY
"$STAGE/bin/python" -m pip install --disable-pip-version-check --no-deps --no-build-isolation "$PACKAGE"
rm -rf -- "$PACKAGE"
(cd "$HOME" && "$STAGE/bin/python" -I -B -m monik --help >/dev/null)
(cd "$HOME" && "$STAGE/bin/python" -I -B -m monik init --config "$CONFIG" >/dev/null)
(cd "$HOME" && "$STAGE/bin/python" -I -B -m monik doctor --config "$CONFIG" >/dev/null)
if (( START )); then
  (cd "$HOME" && "$STAGE/bin/python" -I -B -c 'from monik.sandbox import abi; assert abi()>=3, "Landlock ABI >= 3 required; no unsafe fallback"')
fi
mapfile -t SERVER < <(cd "$HOME" && "$STAGE/bin/python" -I -B - "$CONFIG" <<'PY'
from monik.config import load
import sys
c=load(sys.argv[1])
for value in (c['bind'],c['port'],c.get('tls_cert') or '',c.get('tls_key') or '',c.get('tls_ca') or ''):
    print(value)
PY
)
BIND=${SERVER[0]}; PORT=${SERVER[1]}; TLS_CERT=${SERVER[2]}; TLS_KEY=${SERVER[3]}; TLS_CA=${SERVER[4]}
if [[ -n $TLS_CERT || -n $TLS_KEY || -n $TLS_CA ]]; then
  [[ -n $TLS_CERT && -n $TLS_KEY && -n $TLS_CA ]] || { echo 'TLS-конфигурация неполна: нужны cert, key и публичный tls_ca.' >&2; exit 1; }
  SCHEME=https
else
  SCHEME=http
fi
if [[ $BIND != 127.0.0.1 ]]; then
  (( PORT >= 1024 )) || { echo 'LAN на порту ниже 1024 требует отдельную system-службу с capability.' >&2; exit 1; }
  [[ -n $TLS_CERT && -n $TLS_KEY && -n $TLS_CA ]] || { echo 'LAN user-служба требует cert, key и публичный tls_ca.' >&2; exit 1; }
  DESCRIPTION='monik read-only Codex Observatory (HTTPS LAN)'
else
  DESCRIPTION='monik read-only Codex Observatory'
fi

mkdir -p "$ROLLBACK"
if [[ -f $LAUNCHER ]]; then cp -a -- "$LAUNCHER" "$ROLLBACK/launcher"; fi
if [[ -f $UNIT ]]; then cp -a -- "$UNIT" "$ROLLBACK/unit"; fi

rollback() {
  local code=$?
  trap - EXIT INT TERM
  if (( MUTATED )); then
    systemctl --user stop monik.service >/dev/null 2>&1 || true
    if (( NEW_VENV )); then rm -rf -- "$ROOT/.venv"; fi
    if [[ -n $OLD_VENV && -d $OLD_VENV ]]; then mv -- "$OLD_VENV" "$ROOT/.venv"; fi
    if [[ -f $ROLLBACK/launcher ]]; then cp -a -- "$ROLLBACK/launcher" "$LAUNCHER"; else rm -f -- "$LAUNCHER"; fi
    if [[ -f $ROLLBACK/unit ]]; then cp -a -- "$ROLLBACK/unit" "$UNIT"; else rm -f -- "$UNIT"; fi
    systemctl --user daemon-reload >/dev/null 2>&1 || true
    if (( WAS_ENABLED )); then systemctl --user enable monik.service >/dev/null 2>&1 || true
    else systemctl --user disable monik.service >/dev/null 2>&1 || true
    fi
    if (( WAS_ACTIVE )); then systemctl --user start monik.service >/dev/null 2>&1 || true; fi
  fi
  rm -rf -- "$STAGE"
  rm -rf -- "$PACKAGE"
  if (( code )); then echo "Установка не завершена; прежний user-состав восстановлен из $ROLLBACK" >&2; fi
  exit "$code"
}
trap rollback EXIT INT TERM

MUTATED=1
if (( USER_ACTIVE )); then systemctl --user stop monik.service; fi
DB=$(cd "$HOME" && "$STAGE/bin/python" -I -B -c 'from monik.config import load;from pathlib import Path;import sys;print(Path(load(sys.argv[1])["data_dir"])/"observatory.sqlite")' "$CONFIG")
if [[ -f $DB ]]; then
  BACKUP=$STATE/backups/observer-$STAMP.sqlite
  mkdir -p "$STATE/backups";chmod 700 "$STATE/backups"
  (cd "$HOME" && "$STAGE/bin/python" -I -B -m monik backup --config "$CONFIG" "$BACKUP" >/dev/null)
fi

if [[ -d $ROOT/.venv ]]; then
  [[ ! -L $ROOT/.venv && $(stat -c %u -- "$ROOT/.venv") == "$EUID" ]] || { echo 'Не заменяю небезопасный .venv.' >&2; exit 1; }
  OLD_VENV=$ROLLBACK/venv
  mv -- "$ROOT/.venv" "$OLD_VENV"
fi
mv -- "$STAGE" "$ROOT/.venv";STAGE=$ROOT/.venv.install.consumed;NEW_VENV=1

launcher_tmp=$(mktemp "$HOME/.local/bin/.monik.XXXXXX")
printf '#!/usr/bin/env bash\n# Generated by monik installer\nset -euo pipefail\nexec %q -I -B -m monik "$@"\n' "$ROOT/.venv/bin/python" > "$launcher_tmp"
chmod 700 "$launcher_tmp";mv -fT -- "$launcher_tmp" "$LAUNCHER"

DATA=$(cd "$HOME" && "$ROOT/.venv/bin/python" -I -B -c 'from monik.config import load;import sys;print(load(sys.argv[1])["data_dir"])' "$CONFIG")
unit_tmp=$(mktemp "$HOME/.config/systemd/user/.monik.service.XXXXXX")
cat > "$unit_tmp" <<UNIT
# Generated by monik installer
[Unit]
Description=$DESCRIPTION
After=network.target
[Service]
Type=simple
WorkingDirectory=$HOME
Environment=PYTHONDONTWRITEBYTECODE=1
ExecStart=$ROOT/.venv/bin/python -I -B -m monik serve --config $CONFIG
Restart=on-failure
RestartSec=5
TimeoutStopSec=20
UMask=0077
NoNewPrivileges=true
ProtectSystem=strict
ProtectHome=read-only
ReadWritePaths=$DATA
PrivateTmp=true
Nice=10
[Install]
WantedBy=default.target
UNIT
chmod 600 "$unit_tmp";mv -fT -- "$unit_tmp" "$UNIT"
systemctl --user daemon-reload
if (( START )); then
  systemctl --user enable --now monik.service
  "$ROOT/.venv/bin/python" -I -B - "$CONFIG" <<'PY'
import sys,time
from monik.config import load
from monik.client import Client
c=load(sys.argv[1]);deadline=time.monotonic()+12
while True:
    try:
        Client(c).get('overview');break
    except ValueError:
        if time.monotonic()>=deadline: raise
        time.sleep(.1)
PY
else
  systemctl --user disable monik.service >/dev/null 2>&1 || true
fi

MUTATED=0;trap - EXIT INT TERM
rm -rf -- "$STAGE" "$PACKAGE"
printf '\nУстановка завершена. URL: %s://%s:%s\nТокен: %s token\n' "$SCHEME" "$BIND" "$PORT" "$LAUNCHER"
printf 'TUI: %s tui\nЖурнал: journalctl --user -u monik.service -f\nRollback-снимок: %s\n' "$LAUNCHER" "$ROLLBACK"
