#!/usr/bin/env bash
set -euo pipefail
if (( EUID == 0 )); then echo 'Запусти обычным пользователем.' >&2; exit 1; fi
# Only disable the user service made by this project. Persistent history stays intact.
UNIT="$HOME/.config/systemd/user/monik.service"
if [[ -f "$UNIT" ]] && grep -q '^# Generated by monik installer' "$UNIT"; then
  systemctl --user disable --now monik.service || true
  rm -- "$UNIT"
  systemctl --user daemon-reload
fi
if [[ -f "$HOME/.local/bin/monik" ]] && grep -q ' -m monik ' "$HOME/.local/bin/monik"; then rm -- "$HOME/.local/bin/monik"; fi
printf 'Пользовательская служба удалена. История, токен, TLS и репозиторий оставлены.\n'
printf 'Для LAN-службы отдельно: sudo systemctl disable --now monik.service\n'
