#!/usr/bin/env bash
set -euo pipefail
if (( EUID == 0 )); then echo 'Запусти обычным пользователем.' >&2; exit 1; fi
# Only disable the user service made by this project. Persistent history stays intact.
UNIT="$HOME/.config/systemd/user/monik.service"
safe_generated() {
  local path=$1 marker=$2
  [[ ! -L $path && -f $path && $(stat -c %u -- "$path") == "$EUID" && $(stat -c %h -- "$path") == 1 ]] && grep -Eq "$marker" "$path"
}
if [[ -e $UNIT || -L $UNIT ]]; then
  safe_generated "$UNIT" '^# Generated by monik installer' || { echo "Не удаляю чужой или небезопасный unit: $UNIT" >&2; exit 1; }
  systemctl --user disable --now monik.service || true
  rm -- "$UNIT"
  systemctl --user daemon-reload
fi
LAUNCHER="$HOME/.local/bin/monik"
if [[ -e $LAUNCHER || -L $LAUNCHER ]]; then
  safe_generated "$LAUNCHER" '^# Generated by monik installer|exec .+ -m monik ' || { echo "Не удаляю чужой или небезопасный launcher: $LAUNCHER" >&2; exit 1; }
  rm -- "$LAUNCHER"
fi
printf 'Пользовательская служба удалена. История, токен, TLS и репозиторий оставлены.\n'
printf 'Для LAN-службы отдельно: sudo systemctl disable --now monik.service\n'
